#!/bin/bash

echo "🔧 TxPay Configuration Helper"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "This script will help you set up your .env file."
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "📝 Found existing .env file"
else
    echo "📝 Creating .env file from template..."
    cp .env.example .env
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 Step 1: Alchemy API Key"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To get your FREE Alchemy API key:"
echo "  1. Visit: https://dashboard.alchemy.com/"
echo "  2. Sign up (takes 30 seconds)"
echo "  3. Click '+ Create new app'"
echo "  4. Choose: Ethereum → Mainnet"
echo "  5. Copy your API key"
echo ""
read -p "Enter your Alchemy API key: " ALCHEMY_KEY

if [ -z "$ALCHEMY_KEY" ]; then
    echo "❌ No API key provided. You can add it later to .env"
    ALCHEMY_KEY="your_alchemy_api_key_here"
else
    echo "✅ API key saved"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 Step 2: Payment Address"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This is the Ethereum address where you'll receive payments."
echo "For testing, you can use any valid Ethereum address."
echo ""
echo "Examples:"
echo "  - Your MetaMask address"
echo "  - Test address: 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb"
echo ""
read -p "Enter payment address (or press Enter for default): " PAYMENT_ADDR

if [ -z "$PAYMENT_ADDR" ]; then
    PAYMENT_ADDR="0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb"
    echo "✅ Using default test address"
else
    echo "✅ Payment address saved"
fi

# Write to .env
cat > .env << EOF
# TxPay Configuration
# Generated by configure.sh

# Server Configuration
PORT=3000
NODE_ENV=development

# Alchemy API Configuration (Required)
ALCHEMY_API_KEY=$ALCHEMY_KEY
ALCHEMY_NETWORK=eth-mainnet

# x402 Payment Configuration (Required)
PAYMENT_ADDRESS=$PAYMENT_ADDR

# Payment settings
PAYMENT_NETWORK=base-sepolia
PAYMENT_PRICE_PER_QUERY=0.01

# Logging
LOG_LEVEL=info
EOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Configuration Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Your .env file has been updated with:"
echo "   ALCHEMY_API_KEY: ${ALCHEMY_KEY:0:20}..."
echo "   PAYMENT_ADDRESS: $PAYMENT_ADDR"
echo ""
echo "🚀 Next steps:"
echo "   1. npm run dev     (start the server)"
echo "   2. npm test        (run tests)"
echo "   3. npm run demo    (watch the demo again)"
echo ""
echo "📖 Test your setup:"
echo "   curl -H \"X-Payment-Hash: demo\" \\"
echo "     \"http://localhost:3000/api/transfers?address=0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045&maxCount=3\""
echo ""
