version: '3.8'

services:
  txpay:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - PAYMENT_ADDRESS=${PAYMENT_ADDRESS}
      - ALCHEMY_NETWORK=${ALCHEMY_NETWORK:-eth-mainnet}
      - PAYMENT_NETWORK=${PAYMENT_NETWORK:-base-sepolia}
      - PAYMENT_PRICE_PER_QUERY=${PAYMENT_PRICE_PER_QUERY:-0.01}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
